development:
  adapter: mysql2
  database: abundant3_dev
  host: localhost
  username: root
  password: 

test:
  adapter: sqlite3
  database: db/test.sqlite
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite
  pool: 5
  timeout: 5000
